connection_throttle: 4000
disabled_commands: []
groups:
  LRNZ09: [admin]
ip_forward: false
listeners:
- bind_local_address: true
  force_default_server: true
  forced_hosts: {minecraft.lrnz09.me: default}
  host: 0.0.0.0:25577
  max_players: 4
  motd: "              &fA &acreeper &fwalks into a bar... \n                    &f&lEveryone &c&ldies&f&l."
  ping_passthrough: false
  priorities: [default]
  proxy_protocol: false
  query_enabled: true
  query_port: 25577
  tab_list: GLOBAL_PING
  tab_size: 60
log_commands: true
network_compression_threshold: 256
online_mode: true
permissions:
  admin: [
    bungeecord.command.alert,
    bungeecord.command.end,
    bungeecord.command.ip,
    bungeecord.command.reload,
    bungeecord.command.server
  ]
  default: [bungeecord.command.list]
player_limit: -1
prevent_proxy_connections: true
servers:
  default: {
    address: 'server:25565',
    motd: "              &fA &acreeper &fwalks into a bar... \n                    &f&lEveryone &c&ldies&f&l.",
    restricted: false
  }
stats: df0cff65-00f3-4656-8ca0-406026705f91
timeout: 30000
