version: '3.4'

services:

  traefik:
    command: --docker --docker.swarmmode --docker.domain=lrnz09.me --docker.watch --logLevel=DEBUG --web
    deploy:
      placement:
        constraints: [node.role == manager]
    image: traefik:alpine
    ports: ['80:80', '8080:8080']
    restart: on-failure
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
