version: '3.4'

services:

  traefik:
    deploy:
      labels: {
        traefik.docker.network: traefik,
        traefik.frontend.rule: 'Host:traefik.lrnz09.me',
        traefik.port: 8080
      }
      placement:
        constraints: [node.role == manager]
    image: traefik:alpine
    ports: ['80:80']
    volumes: [
      '/var/run/docker.sock:/var/run/docker.sock',
      './traefik.toml:/etc/traefik/traefik.toml'
    ]
