version: '3.6'

services:

  traefik:
    deploy:
      labels: {
        traefik.docker.network: traefik_default,
        traefik.frontend.rule: 'Host: traefik.lorenzo.cf',
        traefik.port: 7999
      }
      placement:
        constraints: [node.role == manager]
    image: traefik:alpine
    ports: ['80:80']
    volumes: [
      '/home/lrnz09/docker/traefik/traefik.toml:/etc/traefik/traefik.toml',
      '/var/run/docker.sock:/var/run/docker.sock'
    ]
