version: '3.6'

services:

  agent:
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
    environment:
      AGENT_CLUSTER_ADDR: agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    image: portainer/agent
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']

  portainer:
    command: -H tcp://agent:9001 --tlsskipverify
    deploy:
      labels: {
        traefik.docker.network: traefik_default,
        traefik.frontend.rule: 'Host: portainer.lorenzo.cf',
        traefik.port: 9000
      }
    image: portainer/portainer
    volumes: ['portainer_data:/data']

networks:
  default:
    external: true
    name: traefik_default

volumes:
  portainer_data:
