version: '3.6'

services:
  server:
    deploy:
      replicas: 1
    environment: {
      CONSOLE: 'false',
      EULA: 'true',
      GUI: 'false',
      JVM_XX_OPTS: '-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50
        -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80
        -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts',
      # MEMORY: 1G,
      # ONLINE_MODE: 'false',
      OPS: LRNZ09,
      PVP: 'false',
      SEED: '871585827',
      # TYPE: bukkit,
      # VERSION: snapshot
      # WHITELIST: 'LRNZ09 PikateaYt'
    }
    image: itzg/minecraft-server
    ports: ['2052:25565', '2052:25565/udp']
    volumes: ['minecraft_data:/data']

volumes:
  minecraft_data:
