version: '3.4'

services:

  bungeecord:
    deploy:
      placement:
        constraints: [node.role == manager]
    image: itzg/bungeecord
    ports: ['2052:25577', '2052:25577/udp']
    volumes: ['./bungeecord/:/server']

  vanilla:
    deploy:
      placement:
        constraints: [node.role == worker]
    environment: {
      CONSOLE: 'false',
      EULA: 'true',
      GUI: 'false',
      JVM_XX_OPTS: '-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts',
      MEMORY: 1G,
      ONLINE_MODE: 'false',
      OPS: LRNZ09,
      PVP: 'false',
      SEED: '4388092437280786657',
    }
    image: itzg/minecraft-server
    volumes: ['./vanilla:/data']
