version: '3.4'

services:

  ghost:
    container_name: ghost
    deploy:
      mode: replicated
      replicas: 3
      restart_policy: {condition: on-failure, delay: 5s, max_attempts: 3, window: 10s}
      update_config: {delay: 10s, failure_action: rollback, order: start-first, parallelism: 2}
    image: ghost:alpine
    restart: on-failure
    volumes: [
      './config.json:/var/lib/ghost/config.production.json',
      './content:/var/lib/ghost/content'
    ]
