version: '3.6'

services:

  redirect:
    deploy:
      labels: {
        traefik.docker.network: traefik_default,
        traefik.frontend.priority: 1,
        traefik.frontend.rule: 'HostRegexp: {catchall:.*}',
        traefik.port: 8000
      }
      placement:
        constraints: [node.role == manager]
    environment: {
      HTTP_PORT: '8000',
      REDIRECT: 'https://lorenzo.cf',
    }
    image: cusspvz/redirect

networks:
  default:
    external: true
    name: traefik_default
